export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_REVIEWS_START = 'GET_REVIEWS_START';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';

export const GET_RATING_START = 'GET_RATING_START';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_RATING_FAIL = 'GET_RATING_FAIL';

export const CREATE_REVIEWS_START = "CREATE_REVIEWS_START";
export const CREATE_REVIEWS_FAIL = "CREATE_REVIEWS_FAIL";
export const CREATE_REVIEWS_SUCCESS = "CREATE_REVIEWS_SUCCESS";

export const GET_USERBASEDKNN_START = 'GET_USERBASEDKNN_START';
export const GET_USERBASEDKNN_SUCCESS = 'GET_USERBASEDKNN_SUCCESS';
export const GET_USERBASEDKNN_FAIL = 'GET_USERBASEDKNN_FAIL';

export const GET_ITEMBASEDKNN_START = 'GET_ITEMBASEDKNN_START';
export const GET_ITEMBASEDKNN_SUCCESS = 'GET_ITEMBASEDKNN_SUCCESS';
export const GET_ITEMBASEDKNN_FAIL = 'GET_ITEMBASEDKNN_FAIL';

export const GET_GENRESCHOICES_START = 'GET_GENRESCHOICES_START';
export const GET_GENRESCHOICES_SUCCESS = 'GET_GENRESCHOICES_SUCCESS';
export const GET_GENRESCHOICES_FAIL = 'GET_GENRESCHOICES_FAIL';

export const CREATE_GENRESCHOICES_START = "CREATE_GENRESCHOICES_START";
export const CREATE_GENRESCHOICES_FAIL = "CREATE_GENRESCHOICES_FAIL";
export const CREATE_GENRESCHOICES_SUCCESS = "CREATE_GENRESCHOICES_SUCCESS";

export const GET_FAVOURITEMOVIE_START = "GET_FAVOURITEMOVIE_START";
export const GET_FAVOURITEMOVIE_FAIL = "GET_FAVOURITEMOVIE_FAIL";
export const GET_FAVOURITEMOVIE_SUCCESS = "GET_FAVOURITEMOVIE_SUCCESS";

export const CREATE_FAVOURITEMOVIE_START = "CREATE_FAVOURITEMOVIE_START";
export const CREATE_FAVOURITEMOVIE_FAIL = "CREATE_FAVOURITEMOVIE_FAIL";
export const CREATE_FAVOURITEMOVIE_SUCCESS = "CREATE_FAVOURITEMOVIE_SUCCESS";

export const DELETE_FAVOURITEMOVIE_START = "DELETE_FAVOURITEMOVIE_START";
export const DELETE_FAVOURITEMOVIE_FAIL = "DELETE_FAVOURITEMOVIE_FAIL";
export const DELETE_FAVOURITEMOVIE_SUCCESS = "DELETE_FAVOURITEMOVIE_SUCCESS";

/**------------------ Movielens data favourite mvoie --------------- */
export const GET_FAVOURITEMOVIELENS_START = "GET_FAVOURITEMOVIELENS_START";
export const GET_FAVOURITEMOVIELENS_FAIL = "GET_FAVOURITEMOVIELENS_FAIL";
export const GET_FAVOURITEMOVIELENS_SUCCESS = "GET_FAVOURITEMOVIELENS_SUCCESS";

export const CREATE_FAVOURITEMOVIELENS_START = "CREATE_FAVOURITEMOVIELENS_START";
export const CREATE_FAVOURITEMOVIELENS_FAIL = "CREATE_FAVOURITEMOVIELENS_FAIL";
export const CREATE_FAVOURITEMOVIELENS_SUCCESS = "CREATE_FAVOURITEMOVIELENS_SUCCESS";

export const DELETE_FAVOURITEMOVIELENS_START = "DELETE_FAVOURITEMOVIELENS_START";
export const DELETE_FAVOURITEMOVIELENS_FAIL = "DELETE_FAVOURITEMOVIELENS_FAIL";
export const DELETE_FAVOURITEMOVIELENS_SUCCESS = "DELETE_FAVOURITEMOVIELENS_SUCCESS";